"""The places' layout (doors, lanterns, walls, the Market's egg stand and goods, the mill's
sails, 1.0's named anchors) from tools/valley/places.json (written by
tools/blender/valley_places.py) into src/core/places_data.inc, for core/place_layout.

  python tools/valley/gen_places.py
"""
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ORDER = ["den", "market", "stone", "sanctuary", "vault", "trailhead", "arena", "lake", "keeper", "isles",
         "orchard", "mill", "grotto", "ruins", "caldera", "glade", "cove", "hollow"]  # core/valley ValleyPlace


def f(v):
    return f"{v:.3f}f"


def anchor_points(value):
    """A named anchor's points: one point ([x, y] or [x, y, z]) or a list of them; each as
    (x, y, third), the third 0 when it isn't given."""
    pts = [value] if isinstance(value[0], (int, float)) else value
    out = []
    for q in pts:
        assert 2 <= len(q) <= 3, q
        out.append((q[0], q[1], q[2] if len(q) == 3 else 0.0))
    return out


def main():
    places = json.load(open(os.path.join(ROOT, "tools", "valley", "places.json"), encoding="utf-8"))["places"]
    assert list(places) == ORDER, list(places)
    solids, rows = [], []
    for pid in ORDER:
        p = places[pid]
        first = len(solids)
        solids += p["solids"]
        door, lantern = p.get("door"), p.get("lantern")
        rows.append("    {%s, %s, {%s, %s}, %s, {%s, %s, %s}, %d, %d, %s},  // %s" % (
            f(p["flat"]), "true" if door else "false", f(door[0] if door else 0), f(door[1] if door else 0),
            "true" if lantern else "false", *(f(v) for v in (lantern or [0, 0, 0])), first, len(p["solids"]),
            f(p.get("water_z", 0.0)), pid))
    m, mill = places["market"], places["mill"]
    out = ["// Generated by tools/valley/gen_places.py from tools/valley/places.json: do not edit.",
           "// Each place's layout in its own frame (metres, +Y its front, +X its right, z up from the ground).",
           "",
           "struct PlaceRow {",
           "    float flat;",
           "    bool hasDoor;",
           "    float door[2];",
           "    bool hasLantern;",
           "    float lantern[3];",
           "    int firstSolid, solids;",
           "    float waterZ;",
           "};",
           "",
           "const float kPlaceSolids[][3] = {"]
    for x, y, r in solids:
        out.append(f"    {{{f(x)}, {f(y)}, {f(r)}}},")
    out += ["};", "", "const PlaceRow kPlaceRows[] = {"] + rows + ["};", ""]
    out.append("const float kMarketEggStand[3] = {%s};" % ", ".join(f(v) for v in m["egg_stand"]))
    out.append("const float kMarketGoods[4][3] = {%s};" % ", ".join(
        "{%s}" % ", ".join(f(v) for v in g) for g in m["goods_spots"]))
    out.append("const float kMillHub[3] = {%s};" % ", ".join(f(v) for v in mill["hub"]))
    out.append("const float kMillAxis[3] = {%s};" % ", ".join(f(v) for v in mill["hub_axis"]))
    out.append("")
    # Named anchors (1.0): where things happen at a place, by name, in its frame.
    points, anchors = [], []
    for k, pid in enumerate(ORDER):
        for name, value in places[pid].get("anchors", {}).items():
            pts = anchor_points(value)
            anchors.append('    {%d, "%s", %d, %d},  // %s' % (k, name, len(points), len(pts), pid))
            points += pts
    out += ["struct AnchorRow {",
            "    int place;",
            "    const char* name;",
            "    int first, count;",
            "};",
            "",
            "const float kAnchorPoints[][3] = {"]
    out += ["    {%s, %s, %s}," % (f(x), f(y), f(z)) for x, y, z in points] or ["    {0.0f, 0.0f, 0.0f},"]
    out += ["};", "", "const AnchorRow kAnchorRows[] = {"] + (anchors or ['    {-1, "", 0, 0},']) + ["};", ""]
    path = os.path.join(ROOT, "src", "core", "places_data.inc")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"[places] {path}: {len(ORDER)} places, {len(solids)} walls, {len(anchors)} anchors ({len(points)} points)")


if __name__ == "__main__":
    main()
