"""The places' layout (doors, lanterns, walls, the Market's egg stand and goods, the mill's
sails) from tools/valley/places.json (written by tools/blender/valley_places.py) into
src/core/places_data.inc, for core/place_layout.

  python tools/valley/gen_places.py
"""
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ORDER = ["den", "market", "stone", "sanctuary", "vault", "trailhead", "arena", "lake", "keeper", "isles",
         "orchard", "mill", "grotto", "ruins"]  # core/valley ValleyPlace


def f(v):
    return f"{v:.3f}f"


def main():
    places = json.load(open(os.path.join(ROOT, "tools", "valley", "places.json"), encoding="utf-8"))["places"]
    assert list(places) == ORDER, list(places)
    solids, rows = [], []
    for pid in ORDER:
        p = places[pid]
        first = len(solids)
        solids += p["solids"]
        door, lantern = p.get("door"), p.get("lantern")
        rows.append("    {%s, %s, {%s, %s}, %s, {%s, %s, %s}, %d, %d, %s},  // %s" % (
            f(p["flat"]), "true" if door else "false", f(door[0] if door else 0), f(door[1] if door else 0),
            "true" if lantern else "false", *(f(v) for v in (lantern or [0, 0, 0])), first, len(p["solids"]),
            f(p.get("water_z", 0.0)), pid))
    m, mill = places["market"], places["mill"]
    out = ["// Generated by tools/valley/gen_places.py from tools/valley/places.json: do not edit.",
           "// Each place's layout in its own frame (metres, +Y its front, +X its right, z up from the ground).",
           "",
           "struct PlaceRow {",
           "    float flat;",
           "    bool hasDoor;",
           "    float door[2];",
           "    bool hasLantern;",
           "    float lantern[3];",
           "    int firstSolid, solids;",
           "    float waterZ;",
           "};",
           "",
           "const float kPlaceSolids[][3] = {"]
    for x, y, r in solids:
        out.append(f"    {{{f(x)}, {f(y)}, {f(r)}}},")
    out += ["};", "", "const PlaceRow kPlaceRows[] = {"] + rows + ["};", ""]
    out.append("const float kMarketEggStand[3] = {%s};" % ", ".join(f(v) for v in m["egg_stand"]))
    out.append("const float kMarketGoods[4][3] = {%s};" % ", ".join(
        "{%s}" % ", ".join(f(v) for v in g) for g in m["goods_spots"]))
    out.append("const float kMillHub[3] = {%s};" % ", ".join(f(v) for v in mill["hub"]))
    out.append("const float kMillAxis[3] = {%s};" % ", ".join(f(v) for v in mill["hub_axis"]))
    out.append("")
    path = os.path.join(ROOT, "src", "core", "places_data.inc")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"[places] {path}: {len(ORDER)} places, {len(solids)} walls")


if __name__ == "__main__":
    main()
