"""The people's colours (tools/people/looks.py) as a C++ table for src/core/people.cpp:
src/core/people_looks.inc.

  python tools/people/gen_looks.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import looks  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
VILLAGER_ORDER = ["keeper", "market", "sanctuary", "steward", "child", "traveller"]  # core/villagers Villager


def rgb(c):
    return "{%d, %d, %d}" % tuple(c)


def main():
    out = ["// Generated by tools/people/gen_looks.py from tools/people/looks.py: do not edit.",
           "// sRGB bytes, as the 3DS shows them; palette slots in core/model.hpp Palette order.", ""]
    out.append("const Rgb kSkinTones[] = {%s};" % ", ".join(rgb(c) for _, c in looks.SKIN_TONES))
    out.append("const Rgb kHairColours[] = {%s};" % ", ".join(rgb(c) for _, c in looks.HAIR_COLOURS))
    out.append("const Rgb kOutfits[][2] = {%s};" % ", ".join("{%s, %s}" % (rgb(a), rgb(p)) for _, a, p in looks.OUTFITS))
    out.append("const char* const kSkinNames[] = {%s};" % ", ".join('"%s"' % n for n, _ in looks.SKIN_TONES))
    out.append("const char* const kHairColourNames[] = {%s};" % ", ".join('"%s"' % n for n, _ in looks.HAIR_COLOURS))
    out.append("const char* const kOutfitNames[] = {%s};" % ", ".join('"%s"' % n for n, _, _ in looks.OUTFITS))
    fixed = looks.player_palette(0, 0, 0)
    out.append("const Rgb kPlayerFixed[] = {%s};  // the slots the creator leaves" % ", ".join(
        rgb(fixed[s]) for s in looks.SLOTS))
    out.append("const Rgb kVillagerPalettes[][10] = {")
    for vid in VILLAGER_ORDER:
        p = looks.VILLAGERS[vid]
        out.append("    {%s},  // %s" % (", ".join(rgb(p[s]) for s in looks.SLOTS), vid))
    out.append("};")
    out.append("")
    path = os.path.join(ROOT, "src", "core", "people_looks.inc")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"[people] {path}")


if __name__ == "__main__":
    main()
