#!/usr/bin/env python3
"""Noah's review page for the long run: the new sounds to hear and mark (each take PASS, FAIL for
Claude to regenerate, or FAIL for Noah to regenerate from its prompt), the Suno music to make, and
(as they're ready) the run's other review sections.

  python tools/review/make_review.py      -> build/review/index.html + build/review/{sfx,synth}/*.wav

Sounds: every manifest entry (tools/audio/sfx_manifest.json) whose takes were generated by
tools/audio/eleven_sfx.py ("eleven:" takes, with their prompt), in batch order; the game's files
(romfs/sfx) are what's played, so they're heard as the game has them. Each one's synthesised
stand-in (the file before, from git at SYNTH_COMMIT) is there to compare. Music: the prompts in
docs/audio/suno-music-batch-4.md. Extra sections: docs/review/*.html fragments, in name order.

The page is published as an Artifact with the `db` capability; the marks land in its database:
collection `sounds` (a document per slug: {takes: {"1": "pass"|"regen-claude"|"regen-noah"},
note}) and `music` ({status: "todo"|"made"|"skip", note}), where Claude reads them back.
"""
from __future__ import annotations

import html
import json
import re
import shutil
import subprocess
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "build" / "review"
MANIFEST = ROOT / "tools" / "audio" / "sfx_manifest.json"
SYNTH_COMMIT = "4014997"  # (romfs/sfx before batch 4: the synthesised stand-ins)
RUN_READY = True  # the run's checklist on the page (once the build is ready for the 3DS)
RUN_DOC = "docs/plan/hardware-check-6.md"  # the run's steps
RUN_KEY = "run21d"      # its database collection (each run its own: run 20's notes stay under `run`)
LABS = []              # banner labs to mark Held/Froze this run (none in run 21)
SHOW_SOUNDS = False    # the sounds and music sections (Noah: not needed for run 21)
PAGE_TITLE = "Emberclutch Run 21, take 4 (0.9.11)"  # (the long run's own page was "Emberclutch Review")
BATCHES = ["docs/audio/sfx-batch-4.json", "docs/audio/sfx-life-prompts.json", "docs/audio/sfx-duels-prompts.json"]

# Where each sound plays (what to listen for), by slug.
WHERE = {
    "hop-on": "Climbing onto your grown dragon to ride (A by its side).",
    "hop-off": "Getting down from riding.",
    "nuzzle": "Your dragon rubbing its head against you when its Love is high.",
    "shutter": "Taking a photo (the camera button in the den and outside).",
    "equip": "Putting on an accessory in the wardrobe.",
    "swipe": "A body move in a battle (the lunge's whoosh). Three takes, played in turn.",
    "hit": "A move landing in a battle. Three takes, played in turn.",
    "hit-big": "A super-effective or critical hit.",
    "whiff": "A move that misses.",
    "faint": "A dragon too tired to go on at a battle's end (never hurt).",
    "cast": "Casting the line at Driftwood Cove.",
    "plop": "The bobber landing in the water.",
    "bite": "A fish taking the bait.",
    "reel": "Reeling in (repeats quietly while you reel).",
    "shell-pick": "Picking up a shell on the cove's beach.",
    "ice-crack": "Ice cracking in Frostspire Hollow (a frost move, the floor's ice).",
    "step-sand": "Your steps on the cove's sand. Three takes, played in turn.",
    "step-snow": "Your steps in the snow (the north, the Hollow). Three takes, played in turn.",
    "burst": "A burst of speed while flying (a race's boost).",
    "brake": "Braking in the air (wings thrown wide).",
    "amb-cove": "The loop under Driftwood Cove: waves on the beach.",
    "amb-caldera": "The loop under Emberpeak Caldera: the crater's rumble and embers.",
    "amb-hollow": "The loop under Frostspire Hollow: cold wind and drips.",
    "amb-rush": "The rushing wind that rises with your speed in the air.",
}


def load_json(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else []


def seconds(p: Path) -> float:
    with wave.open(str(p)) as w:
        return w.getnframes() / w.getframerate()


def takes_of(slug: str, n: int) -> list[str]:
    return [f"{slug}.wav" if i == 1 else f"{slug}-{i}.wav" for i in range(1, n + 1)]


def sounds() -> list[dict]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    order, meta = [], {}
    for b in BATCHES:
        for s in load_json(ROOT / b):
            if s["slug"] not in meta:
                order.append(s["slug"])
                meta[s["slug"]] = s
    out = []
    for slug in order:
        e = manifest.get(slug)
        if not e or not any(t.startswith("eleven:") for t in e.get("takes", [])):
            continue
        files = takes_of(slug, len(e["takes"]) + e.get("take_offset", 0))  # (hit: the synth's three, then its generated take)
        (OUT / "sfx").mkdir(parents=True, exist_ok=True)
        lens = []
        for f in files:
            shutil.copyfile(ROOT / "romfs" / "sfx" / f, OUT / "sfx" / f)
            lens.append(seconds(OUT / "sfx" / f))
        synth = None  # the stand-in it replaces, if there was one
        try:
            data = b""
            for commit in (SYNTH_COMMIT, "d989a57"):  # (before batch 4; the duels' stand-ins came with their merge)
                r = subprocess.run(["git", "show", f"{commit}:romfs/sfx/{slug}.wav"], cwd=ROOT, capture_output=True)
                if r.returncode == 0:
                    data = r.stdout
                    break
            if not data:
                raise subprocess.CalledProcessError(1, "git show")
            (OUT / "synth").mkdir(parents=True, exist_ok=True)
            (OUT / "synth" / f"{slug}.wav").write_bytes(data)
            synth = f"synth/{slug}.wav"
        except subprocess.CalledProcessError:
            pass
        out.append({"slug": slug, "prompt": e.get("prompt", meta[slug].get("prompt", "")),
                    "duration": e.get("duration", meta[slug].get("duration")), "loop": e["kind"] == "loop",
                    "where": WHERE.get(slug, meta[slug].get("where", "")), "files": [f"sfx/{f}" for f in files],
                    "lens": lens, "synth": synth})
    return out


# Sounds made here at Noah's asking (not generated): to hear on the page too.
MADE = {
    "rabbit-hop": ("Made in the synth, as you asked: soft round bounds with a springy lift and a brush of grass.",
                   "A rabbit or snow hare bolting (and in the chase)."),
    "bird-flutter": ("Built from the chirps you kept (takes 1 and 3), overlapping, pitched up and down, fading off.",
                     "A flock scattering as you or your dragon come near."),
}


def made_sounds() -> list[dict]:
    out = []
    for slug, (how, where) in MADE.items():
        files = [f for f in takes_of(slug, 4) if (ROOT / "romfs" / "sfx" / f).exists()]
        (OUT / "sfx").mkdir(parents=True, exist_ok=True)
        for f in files:
            shutil.copyfile(ROOT / "romfs" / "sfx" / f, OUT / "sfx" / f)
        out.append({"slug": slug, "prompt": how, "duration": "made", "loop": False, "where": where,
                    "files": [f"sfx/{f}" for f in files], "lens": [seconds(OUT / "sfx" / f) for f in files], "synth": None})
    return out


def music() -> list[dict]:
    md = (ROOT / "docs" / "audio" / "suno-music-batch-4.md").read_text(encoding="utf-8")
    rows = {m.group(1): (m.group(2).strip(), m.group(3).strip(), m.group(4).strip())
            for m in re.finditer(r"^\| \d+ \| `([a-z0-9-]+)` \| ([^|]+)\| ([^|]+)\| ([^|]+)\|", md, re.M)}
    out = []
    for part in md.split("\n## ")[1:]:  # a section a track
        head = re.match(r'\d+\. "([^"]+)" — (.*)', part)
        slug = re.search(r"\*\*Slug:\*\* `([a-z0-9-]+)`", part)
        mood = re.search(r"\*\*Mood:\*\* (.*?)\n\n", part, re.S)
        style = re.search(r"```\n(.*?)```", part, re.S)
        if not (head and slug and style):
            continue
        kind, plays, prio = rows.get(slug.group(1), ("", "", ""))
        seam = ROOT / "assets" / "audio" / "music" / "previews" / f"{slug.group(1)}.seam-preview.wav"
        heard = None
        if seam.exists() and (ROOT / "romfs" / "music" / f"{slug.group(1)}.ogg").exists():
            (OUT / "music").mkdir(parents=True, exist_ok=True)
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(seam), "-ac", "1", "-b:a", "96k",
                            str(OUT / "music" / f"{slug.group(1)}.seam.mp3")], check=True)
            heard = f"music/{slug.group(1)}.seam.mp3"
        out.append({"seam": heard, "slug": slug.group(1), "title": head.group(1), "sub": head.group(2).strip(),
                    "mood": " ".join(mood.group(1).split()) if mood else "", "style": style.group(1).strip(),
                    "kind": kind.replace("**", ""), "plays": plays, "priority": prio.replace("**", "")})
    return out


def inline_md(text: str) -> str:
    """The run list's markdown, inline: **bold**, `code`, [links](...), escaped otherwise."""
    t = html.escape(" ".join(text.split()), quote=False)
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"`([^`]+)`", r"<code>\1</code>", t)
    t = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", t)  # (links to repo docs mean nothing on the page)
    return t


def run_list(path: str = RUN_DOC) -> dict:
    """The run's steps from its doc: each '## N. Title' section, its numbered steps (or its text)."""
    p = ROOT / path
    if not p.exists():
        return {}
    md = p.read_text(encoding="utf-8")
    title = md.split("\n", 1)[0].lstrip("# ").strip()
    intro = md.split("\n## ", 1)[0].split("\n", 1)[1].strip()
    sections = []
    for part in md.split("\n## ")[1:]:
        head, _, body = part.partition("\n")
        m = re.match(r"(\d+)\. (.*)", head.strip())
        steps, lead, cur = [], [], None
        for line in body.split("\n"):
            s = re.match(r"(\d+)\. (.*)", line) or re.match(r"()- (.*)", line)  # (numbered steps, or bullets)
            if s:
                cur = [s.group(2)]
                steps.append(cur)
            elif line.startswith("   ") and cur is not None:
                cur.append(line.strip())
            elif line.strip() and not steps:
                lead.append(line.strip())
        sec_id = f"s{m.group(1)}" if m else re.sub(r"[^a-z]+", "-", head.lower()).strip("-")
        if not steps and lead and m:  # (a section that's one paragraph: one thing to tick)
            steps, lead = [lead], []
        sections.append({"id": sec_id, "title": m.group(2) if m else head.strip(), "lead": inline_md(" ".join(lead)),
                         "steps": [{"id": f"{sec_id}-{i + 1}", "text": inline_md(" ".join(st))} for i, st in enumerate(steps)],
                         "send": not m, "labs": "banner lab" in head.lower()})
    return {"title": title, "intro": inline_md(intro), "sections": sections, "labs": LABS, "key": RUN_KEY}


def fragments() -> str:
    d = ROOT / "docs" / "review"
    return "\n".join(p.read_text(encoding="utf-8") for p in sorted(d.glob("*.html"))) if d.exists() else ""


def main() -> None:
    shutil.rmtree(OUT, ignore_errors=True)
    OUT.mkdir(parents=True, exist_ok=True)  # (a shell may be sitting in it)
    data = {"sounds": sounds() + made_sounds() if SHOW_SOUNDS else [], "music": music() if SHOW_SOUNDS else [],
            "run": run_list() if RUN_READY else {}}
    page = (Path(__file__).with_name("review_template.html").read_text(encoding="utf-8")
            .replace("/*DATA*/null", json.dumps(data, ensure_ascii=False))
            .replace("/*TITLE*/", PAGE_TITLE)
            .replace("<!--SECTIONS-->", fragments()))
    (OUT / "index.html").write_text(page, encoding="utf-8")
    n = sum(len(s["files"]) for s in data["sounds"])
    print(f"[review] {len(data['sounds'])} sounds ({n} takes), {len(data['music'])} music prompts -> {OUT / 'index.html'}")


if __name__ == "__main__":
    main()
