#!/usr/bin/env python3
"""Noah's review page for the long run: the new sounds to hear and mark (each take PASS, FAIL for
Claude to regenerate, or FAIL for Noah to regenerate from its prompt), the Suno music to make, and
(as they're ready) the run's other review sections.

  python tools/review/make_review.py      -> build/review/index.html + build/review/{sfx,synth}/*.wav

Sounds: every manifest entry (tools/audio/sfx_manifest.json) whose takes were generated by
tools/audio/eleven_sfx.py ("eleven:" takes, with their prompt), in batch order; the game's files
(romfs/sfx) are what's played, so they're heard as the game has them. Each one's synthesised
stand-in (the file before, from git at SYNTH_COMMIT) is there to compare. Music: the prompts in
docs/audio/suno-music-batch-4.md. Extra sections: docs/review/*.html fragments, in name order.

The page is published as an Artifact with the `db` capability; the marks land in its database:
collection `sounds` (a document per slug: {takes: {"1": "pass"|"regen-claude"|"regen-noah"},
note}) and `music` ({status: "todo"|"made"|"skip", note}), where Claude reads them back.
"""
from __future__ import annotations

import html
import json
import re
import shutil
import subprocess
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "build" / "review"
MANIFEST = ROOT / "tools" / "audio" / "sfx_manifest.json"
SYNTH_COMMIT = "4014997"  # (romfs/sfx before batch 4: the synthesised stand-ins)
RUN_READY = True  # the run's checklist on the page (once the build is ready for the 3DS)
RUN_DOC = "docs/plan/hardware-check-10.md"  # the run's steps
RUN_KEY = "run25"       # its database collection (each run its own: run 24's notes stay under `run24`)
LABS = ["25A", "25B", "25C", "25D", "25E", "25F"]  # banner labs to mark Held/Froze this run (run 25: the new banner, D144)
SHOW_SOUNDS = False    # the sounds and music sections (Noah: not needed for run 21)
PAGE_TITLE = "Emberclutch: Skyreach Valley, run 25 (0.10.1): the new banner, and run 24's fixes"  # (the long run's own page was "Emberclutch Review")
BATCHES = ["docs/audio/sfx-batch-4.json", "docs/audio/sfx-life-prompts.json", "docs/audio/sfx-duels-prompts.json"]

# Where each sound plays (what to listen for), by slug.
WHERE = {
    "hop-on": "Climbing onto your grown dragon to ride (A by its side).",
    "hop-off": "Getting down from riding.",
    "nuzzle": "Your dragon rubbing its head against you when its Love is high.",
    "shutter": "Taking a photo (the camera button in the den and outside).",
    "equip": "Putting on an accessory in the wardrobe.",
    "swipe": "A body move in a battle (the lunge's whoosh). Three takes, played in turn.",
    "hit": "A move landing in a battle. Three takes, played in turn.",
    "hit-big": "A super-effective or critical hit.",
    "whiff": "A move that misses.",
    "faint": "A dragon too tired to go on at a battle's end (never hurt).",
    "cast": "Casting the line at Driftwood Cove.",
    "plop": "The bobber landing in the water.",
    "bite": "A fish taking the bait.",
    "reel": "Reeling in (repeats quietly while you reel).",
    "shell-pick": "Picking up a shell on the cove's beach.",
    "ice-crack": "Ice cracking in Frostspire Hollow (a frost move, the floor's ice).",
    "step-sand": "Your steps on the cove's sand. Three takes, played in turn.",
    "step-snow": "Your steps in the snow (the north, the Hollow). Three takes, played in turn.",
    "burst": "A burst of speed while flying (a race's boost).",
    "brake": "Braking in the air (wings thrown wide).",
    "amb-cove": "The loop under Driftwood Cove: waves on the beach.",
    "amb-caldera": "The loop under Emberpeak Caldera: the crater's rumble and embers.",
    "amb-hollow": "The loop under Frostspire Hollow: cold wind and drips.",
    "amb-rush": "The rushing wind that rises with your speed in the air.",
}


def load_json(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else []


def seconds(p: Path) -> float:
    with wave.open(str(p)) as w:
        return w.getnframes() / w.getframerate()


def takes_of(slug: str, n: int) -> list[str]:
    return [f"{slug}.wav" if i == 1 else f"{slug}-{i}.wav" for i in range(1, n + 1)]


def sounds() -> list[dict]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    order, meta = [], {}
    for b in BATCHES:
        for s in load_json(ROOT / b):
            if s["slug"] not in meta:
                order.append(s["slug"])
                meta[s["slug"]] = s
    out = []
    for slug in order:
        e = manifest.get(slug)
        if not e or not any(t.startswith("eleven:") for t in e.get("takes", [])):
            continue
        files = takes_of(slug, len(e["takes"]) + e.get("take_offset", 0))  # (hit: the synth's three, then its generated take)
        (OUT / "sfx").mkdir(parents=True, exist_ok=True)
        lens = []
        for f in files:
            shutil.copyfile(ROOT / "romfs" / "sfx" / f, OUT / "sfx" / f)
            lens.append(seconds(OUT / "sfx" / f))
        synth = None  # the stand-in it replaces, if there was one
        try:
            data = b""
            for commit in (SYNTH_COMMIT, "d989a57"):  # (before batch 4; the duels' stand-ins came with their merge)
                r = subprocess.run(["git", "show", f"{commit}:romfs/sfx/{slug}.wav"], cwd=ROOT, capture_output=True)
                if r.returncode == 0:
                    data = r.stdout
                    break
            if not data:
                raise subprocess.CalledProcessError(1, "git show")
            (OUT / "synth").mkdir(parents=True, exist_ok=True)
            (OUT / "synth" / f"{slug}.wav").write_bytes(data)
            synth = f"synth/{slug}.wav"
        except subprocess.CalledProcessError:
            pass
        out.append({"slug": slug, "prompt": e.get("prompt", meta[slug].get("prompt", "")),
                    "duration": e.get("duration", meta[slug].get("duration")), "loop": e["kind"] == "loop",
                    "where": WHERE.get(slug, meta[slug].get("where", "")), "files": [f"sfx/{f}" for f in files],
                    "lens": lens, "synth": synth})
    return out


# Sounds made here at Noah's asking (not generated): to hear on the page too.
MADE = {
    "rabbit-hop": ("Made in the synth, as you asked: soft round bounds with a springy lift and a brush of grass.",
                   "A rabbit or snow hare bolting (and in the chase)."),
    "bird-flutter": ("Built from the chirps you kept (takes 1 and 3), overlapping, pitched up and down, fading off.",
                     "A flock scattering as you or your dragon come near."),
}


def made_sounds() -> list[dict]:
    out = []
    for slug, (how, where) in MADE.items():
        files = [f for f in takes_of(slug, 4) if (ROOT / "romfs" / "sfx" / f).exists()]
        (OUT / "sfx").mkdir(parents=True, exist_ok=True)
        for f in files:
            shutil.copyfile(ROOT / "romfs" / "sfx" / f, OUT / "sfx" / f)
        out.append({"slug": slug, "prompt": how, "duration": "made", "loop": False, "where": where,
                    "files": [f"sfx/{f}" for f in files], "lens": [seconds(OUT / "sfx" / f) for f in files], "synth": None})
    return out


def music() -> list[dict]:
    md = (ROOT / "docs" / "audio" / "suno-music-batch-4.md").read_text(encoding="utf-8")
    rows = {m.group(1): (m.group(2).strip(), m.group(3).strip(), m.group(4).strip())
            for m in re.finditer(r"^\| \d+ \| `([a-z0-9-]+)` \| ([^|]+)\| ([^|]+)\| ([^|]+)\|", md, re.M)}
    out = []
    for part in md.split("\n## ")[1:]:  # a section a track
        head = re.match(r'\d+\. "([^"]+)" — (.*)', part)
        slug = re.search(r"\*\*Slug:\*\* `([a-z0-9-]+)`", part)
        mood = re.search(r"\*\*Mood:\*\* (.*?)\n\n", part, re.S)
        style = re.search(r"```\n(.*?)```", part, re.S)
        if not (head and slug and style):
            continue
        kind, plays, prio = rows.get(slug.group(1), ("", "", ""))
        seam = ROOT / "assets" / "audio" / "music" / "previews" / f"{slug.group(1)}.seam-preview.wav"
        heard = None
        if seam.exists() and (ROOT / "romfs" / "music" / f"{slug.group(1)}.ogg").exists():
            (OUT / "music").mkdir(parents=True, exist_ok=True)
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(seam), "-ac", "1", "-b:a", "96k",
                            str(OUT / "music" / f"{slug.group(1)}.seam.mp3")], check=True)
            heard = f"music/{slug.group(1)}.seam.mp3"
        out.append({"seam": heard, "slug": slug.group(1), "title": head.group(1), "sub": head.group(2).strip(),
                    "mood": " ".join(mood.group(1).split()) if mood else "", "style": style.group(1).strip(),
                    "kind": kind.replace("**", ""), "plays": plays, "priority": prio.replace("**", "")})
    return out


def inline_md(text: str) -> str:
    """The run list's markdown, inline: **bold**, `code`, [links](...), escaped otherwise."""
    t = html.escape(" ".join(text.split()), quote=False)
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"`([^`]+)`", r"<code>\1</code>", t)
    t = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", t)  # (links to repo docs mean nothing on the page)
    return t


def run_list(path: str = RUN_DOC) -> dict:
    """The run's steps from its doc: each '## N. Title' section, its numbered steps (or its text)."""
    p = ROOT / path
    if not p.exists():
        return {}
    md = p.read_text(encoding="utf-8")
    title = md.split("\n", 1)[0].lstrip("# ").strip()
    intro = md.split("\n## ", 1)[0].split("\n", 1)[1].strip()
    sections = []
    for part in md.split("\n## ")[1:]:
        head, _, body = part.partition("\n")
        m = re.match(r"(\d+)\. (.*)", head.strip())
        steps, lead, cur = [], [], None
        for line in body.split("\n"):
            s = re.match(r"(\d+)\. (.*)", line) or re.match(r"()- (.*)", line)  # (numbered steps, or bullets)
            if s:
                cur = [s.group(2)]
                steps.append(cur)
            elif line.startswith("   ") and cur is not None:
                cur.append(line.strip())
            elif line.strip() and not steps:
                lead.append(line.strip())
        sec_id = f"s{m.group(1)}" if m else re.sub(r"[^a-z]+", "-", head.lower()).strip("-")
        if not steps and lead and m:  # (a section that's one paragraph: one thing to tick)
            steps, lead = [lead], []
        sections.append({"id": sec_id, "title": m.group(2) if m else head.strip(), "lead": inline_md(" ".join(lead)),
                         "steps": [{"id": f"{sec_id}-{i + 1}", "text": inline_md(" ".join(st))} for i, st in enumerate(steps)],
                         "send": not m, "labs": "banner lab" in head.lower()})
    return {"title": title, "intro": inline_md(intro), "sections": sections, "labs": LABS, "key": RUN_KEY}


# The dragons before 1.0 (Noah: "a list of all of the existing dragons visually and let me PASS/FAIL
# them with comments"): every kind as a hatchling and grown, from tests/autotest/dragons_*.txt's shots
# (build/autotest/dragons_hatchling|grown/dNN-<slug>_top.png), cropped to the dragon. Collection
# `dragons`: a document per kind ({mark: "pass"|"fail", note}).
DRAGONS = False  # (run 21's list, marked; run 22 marks the people instead)


def dragons() -> list[dict]:
    inc = (ROOT / "src" / "core" / "kinds_data.inc").read_text(encoding="utf-8")
    kinds = []
    for m in re.finditer(r'^    \{"([a-z]+)", "([^"]+)", \d+, \{[^}]*\}, \d+, \{[^}]*\}, Rarity::(\w+).*?"([^"]{24,})"', inc, re.M | re.S):
        kinds.append({"slug": m.group(1), "name": m.group(2), "rarity": m.group(3), "blurb": m.group(4)})
    out = []
    (OUT / "dragons").mkdir(parents=True, exist_ok=True)
    for k in kinds:
        pics = {}
        for form, key in (("hatchling", "h"), ("grown", "g")):
            shots = sorted((ROOT / "build" / "autotest" / f"dragons_{form}").glob(f"d??-{k['slug']}_top.png"))
            if not shots:
                continue
            dst = OUT / "dragons" / f"{k['slug']}_{key}.png"
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(shots[0]), "-vf", "crop=258:208:68:26", str(dst)], check=True)
            pics[key] = f"dragons/{dst.name}"
        if pics:
            out.append({**k, **pics})
    return out


# The people before 1.0 (Noah: "2 more 3d models that could replace the general human design in-game ...
# two sets of two (boy and girl) ... One should be more like animal crossing, the other is up to you"):
# tools/people/candidates.py, rendered by `blender -b -P tools/blender/people_model.py -- --candidates
# --out <abs>/build/people_cand --sheets candidates --res 400`. Collection `people`: one document,
# `choice` ({pick: "vil"|"story"|"now", note}).
PEOPLE_SHOTS = ROOT / "build" / "people_cand"
PEOPLE_SETS = [
    {"key": "vil", "title": "Set 1: Villager",
     "blurb": "The Animal Crossing way: a big round head, about half their height, on a small body; dot eyes with a glint, "
              "rosy cheeks, chunky hair. A striped tee and shorts; a collared dress with a bow, and twin tails. About 1.2 m "
              "tall. Their arms are short, so the wave and cheer clips would need their arms raised higher to show."},
    {"key": "story", "title": "Set 2: Storybook",
     "blurb": "My pick: taller, about three heads, with big irised eyes, brows (and her lashes), and a dragon keeper's "
              "clothes. His tunic, hooded capelet with a brass clasp, satchel and boots; her long braid, pinafore over a "
              "puff-sleeved blouse, and an egg carried in a pouch at her hip. About 1.35 m tall."},
]


def people_cands() -> dict:
    if not (PEOPLE_SHOTS / "cand_lineup.png").exists():
        return {}
    (OUT / "people").mkdir(parents=True, exist_ok=True)

    def jpg(name):
        src = PEOPLE_SHOTS / f"cand_{name}.png"
        dst = OUT / "people" / f"{name}.jpg"
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(src), "-q:v", "3", str(dst)], check=True)
        return f"people/{dst.name}"

    sets = []
    for st in PEOPLE_SETS:
        k = st["key"]
        sets.append({**st, "turn": jpg(f"{k}_turn"), "faces": jpg(f"{k}_faces"),
                     "moves": [jpg(f"{k}_boy_moves"), jpg(f"{k}_girl_moves")]})
    return {"lineup": jpg("lineup"), "ride": jpg("ride"), "sets": sets}


# The people in the Storybook look (D138): every body, front and three-quarter (people_model.py
# --sheets models into build/people_sb/tiles), its five portraits (assets/sprites/portraits) and its
# face in all twenty feelings (--sheets feelings), each to PASS or FAIL with a note. Collection
# `looks`: a document per body ({mark: "pass"|"fail", note}).
LOOK_SHOTS = ROOT / "build" / "people_sb"
LOOK_NAMES = {"player_a": "You: the tunic", "player_b": "You: the dress", "keeper": "Old Rowan", "market": "Maple",
              "sanctuary": "Bram", "steward": "Wren", "child": "Pip", "traveller": "Sable", "rook": "Captain Rook"}
PORTRAIT_OF = {"keeper": "rowan", "market": "maple", "sanctuary": "bram", "steward": "wren", "child": "pip",
               "traveller": "sable"}


def looks() -> dict:
    import sys
    sys.path.insert(0, str(ROOT / "tools" / "people"))
    import people  # noqa: E402 (the bodies' own descriptions)
    if not (LOOK_SHOTS / "tiles").exists():
        return {}
    (OUT / "looks").mkdir(parents=True, exist_ok=True)

    def ff(args, dst):
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error"] + args + [str(dst)], check=True)
        return f"looks/{dst.name}"

    out = []
    for pid, build in people.PEOPLE.items():
        front, quarter = (LOOK_SHOTS / "tiles" / f"model_{pid}_{v}.png" for v in ("front", "three_quarter"))
        if not front.exists():
            continue
        item = {"slug": pid, "name": LOOK_NAMES.get(pid, pid.capitalize()),
                "blurb": " ".join((build.__doc__ or "").split()),
                "model": ff(["-i", str(front), "-i", str(quarter), "-filter_complex", "hstack", "-q:v", "3"],
                            OUT / "looks" / f"{pid}.jpg")}
        pname = PORTRAIT_OF.get(pid, pid)
        frames = [ROOT / "assets" / "sprites" / "portraits" / f"{pname}_{k}.png" for k in range(5)]
        if all(f.exists() for f in frames):
            args = []
            for f in frames:
                args += ["-i", str(f)]
            item["faces"] = ff(args + ["-filter_complex", "hstack=inputs=5,scale=iw*2:ih*2:flags=neighbor"],
                               OUT / "looks" / f"{pid}_portraits.png")
        feel = LOOK_SHOTS / f"feelings_{pid}.png"
        if feel.exists():
            item["feelings"] = ff(["-i", str(feel), "-vf", "scale=iw/2:ih/2", "-q:v", "4"], OUT / "looks" / f"{pid}_feelings.jpg")
        out.append(item)
    lineup = LOOK_SHOTS / "lineup.png"
    return {"people": out, "lineup": ff(["-i", str(lineup), "-q:v", "3"], OUT / "looks" / "lineup.jpg") if lineup.exists() else ""}


LOOKS = False  # (run 23: every look passed; their marks stay in `looks`)


def md_html(md: str) -> str:
    """A plan doc's blocks as HTML: paragraphs, bullet and numbered lists, tables, quotes (inline_md inside)."""
    out, para, items, kind, rows, quote = [], [], [], "", [], []

    def flush():
        nonlocal para, items, kind, rows, quote
        if para:
            out.append(f"<p>{inline_md(' '.join(para))}</p>")
        if items:
            out.append(f"<{kind}>" + "".join(f"<li>{inline_md(' '.join(i))}</li>" for i in items) + f"</{kind}>")
        if rows:
            head, body = rows[0], [r for r in rows[1:] if not set("".join(r)) <= set("-: ")]
            out.append("<table><thead><tr>" + "".join(f"<th>{inline_md(c)}</th>" for c in head) + "</tr></thead><tbody>" +
                       "".join("<tr>" + "".join(f"<td>{inline_md(c)}</td>" for c in r) + "</tr>" for r in body) + "</tbody></table>")
        if quote:
            out.append("<blockquote>" + "<br>".join(inline_md(q) if q else "" for q in quote) + "</blockquote>")
        para, items, kind, rows, quote = [], [], "", [], []

    for line in md.split("\n"):
        t = line.strip()
        bullet = re.match(r"- (.*)", t)
        number = re.match(r"\d+\. (.*)", t)
        if not t:
            flush()
        elif t.startswith("|"):
            if not rows:
                flush()
            rows.append([c.strip() for c in t.strip("|").split("|")])
        elif t.startswith(">"):
            if not quote:
                flush()
            quote.append(t[1:].strip())
        elif bullet or number:
            k = "ul" if bullet else "ol"
            if kind != k or para:
                flush()
                kind = k
            items.append([(bullet or number).group(1)])
        elif items and line.startswith(" "):
            items[-1].append(t)
        else:
            if items or rows or quote:
                flush()
            para.append(t)
    flush()
    return "".join(out)


def doc_section(path: str, heading: str) -> str:
    """The text under a '## heading' (or '**heading**' paragraph lead) of a doc, up to the next '## '."""
    md = (ROOT / path).read_text(encoding="utf-8")
    for part in md.split("\n## ")[1:]:
        head, _, body = part.partition("\n")
        if head.strip().startswith(heading):
            return body
    raise KeyError(f"{path}: no section {heading!r}")


# The plans to Keep or Change (D142: the road to 1.0, the guide, the video, YouTube) and the hats' new
# seats (D141); collection `plans`, a document per card ({mark: "keep"|"change", note}).
PLANS = True


def plans() -> list[dict]:
    rel, guide, film = "docs/plan/release-1.0.md", "docs/plan/guide.md", "docs/plan/trailer.md"
    yt = doc_section(film, "YouTube: drafts")
    cards = [
        {"slug": "road", "kicker": "D142", "title": "The road to 1.0: the order of work", "body": md_html(doc_section(rel, "The order"))},
        {"slug": "polish", "kicker": "R1", "title": "What's left for 1.0 (the banner included)", "body": md_html(doc_section(rel, "R1:"))},
        {"slug": "guide", "kicker": "R3 · the guide", "title": "The guide: what it is and what it won't spoil",
         "body": md_html(doc_section(guide, "What it is")) + "<h4>Not spoiled</h4>" + md_html(doc_section(guide, "What it won't spoil"))},
        {"slug": "guide-outline", "kicker": "R3 · the guide", "title": "The guide's outline", "body": md_html(doc_section(guide, "The outline"))},
        {"slug": "video-stack", "kicker": "R6 · the video", "title": "The video: what it is and how it's made",
         "body": md_html(doc_section(film, "What it is")) + md_html(doc_section(film, "The stack"))},
        {"slug": "video-shots", "kicker": "R6 · the video", "title": "The video's shots (a first list)", "body": md_html(doc_section(film, "The shots"))},
        {"slug": "voices", "kicker": "R6 · the video", "title": "Voices: sampled first, picked by you", "body": md_html(doc_section(film, "Voices"))},
        {"slug": "youtube", "kicker": "R7 · YouTube", "title": "The title and description", "body": md_html(yt)},
        {"slug": "hats", "kicker": "D141 · in 0.10.0", "title": "The hats' new seats, every kind",
         "body": md_html("Each hat now sits on the skull: a little back, a little smaller (to 70%) or tipped back, so the eyes "
                         "stay clear and nothing floats. As the den's camera sees them: the straw sunhat, the little top hat, the "
                         "ember crown and the party hat on every kind, grown and as a hatchling. Change: say which kinds."),
         "images": []},
        {"slug": "questions", "kicker": "Before anything goes public", "title": "Questions for you", "ask": True,
         "body": md_html(doc_section(rel, "R2:").split("**Open questions for Noah**", 1)[1].split(":", 1)[1])},
    ]
    shots = ROOT / "build" / "hatsfit"
    (OUT / "plans").mkdir(parents=True, exist_ok=True)
    for name, cap in (("g1", "Grown: Pouncer to Glimmermoth"), ("g2", "Grown: Duskwing to Frostcurl"),
                      ("h1", "Hatchlings: Pouncer to Glimmermoth"), ("h2", "Hatchlings: Duskwing to Frostcurl")):
        src = shots / f"{name}.png"
        if src.exists():
            dst = OUT / "plans" / f"hats_{name}.jpg"
            subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", str(src), "-q:v", "3", str(dst)], check=True)
            cards[8]["images"].append({"src": f"plans/{dst.name}", "cap": cap})
    return cards


# Run 25's cards (D144): the six banner labs, each through the HOME Menu's camera (front, and side as
# the HOME Menu turns it), Keep the ones you like; and the answers to run 24's questions. Collection
# `plans` (slugs banner-25a ...).
BANNERS = [("25A", "A", "Pouncer, with the ink outline"), ("25B", "B", "Blazeplume, with the ink outline"),
           ("25C", "C", "Crestwing, with the ink outline"), ("25D", "D", "Puffback, with the ink outline"),
           ("25E", "E", "Blazeplume, no outline"), ("25F", "F", "Pouncer, no outline")]
PLANS_HEAD = {"nav": "The new banner", "kicker": "D144 · six banner labs on your 3DS",
              "title": "The new banner",
              "intro": "A real baby dragon from the game in its egg: the den model at full detail, smooth, its own skin, under the "
                       "wordmark (as Blender draws it; the HOME Menu's light is a little flatter). Keep the ones you like, Change "
                       "the ones you don't and say why, and name your favourite. Held or froze goes in the run's banner lab step."}


def banners() -> list[dict]:
    (OUT / "plans").mkdir(parents=True, exist_ok=True)
    cards = []
    for lab, src, what in BANNERS:
        d = ROOT / "build" / "banner_v" / src
        images = []
        for name, cap in (("banner3d_big", "Through the HOME Menu's camera"), ("banner3d_side", "Side on, as the HOME Menu turns it")):
            if (d / f"{name}.png").exists():
                dst = OUT / "plans" / f"banner_{src}_{name}.jpg"
                subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", str(d / f"{name}.png"), "-q:v", "3", str(dst)], check=True)
                images.append({"src": f"plans/{dst.name}", "cap": cap})
        kb = round((d / "banner.cgfx").stat().st_size / 1024) if (d / "banner.cgfx").exists() else 0
        cards.append({"slug": f"banner-{lab.lower()}", "kicker": f"Banner lab {lab}", "title": what,
                      "body": md_html(f"Its banner is {kb} KB of the 512 the HOME Menu allows."), "images": images})
    cards.append({"slug": "answers-25", "kicker": "Run 24's questions", "title": "Your questions, answered", "ask": True,
                  "body": md_html(ANSWERS)})
    return cards


ANSWERS = """**Max or xhigh for the video?** Not much better for building it: the film build, the capture and the titles
page are engineering, and xhigh does those as well. Where max earns its cost is the edit, looking hard at every
pass's frames and fixing the worst over more passes. So xhigh to build and capture, max for the edit's critique
passes. A clear reference (the shot list, stills of the look) matters more than either.

- **The contact:** your email is in `CODE_OF_CONDUCT.md` for conduct reports. It'll be public once the repo is;
  say if you'd rather use another address.
- **Suno and ElevenLabs:** your Suno plan covers the music for anything; every paid ElevenLabs plan, your Starter
  included, carries a commercial license, YouTube included (content made on the free plan would need an
  "elevenlabs.io" credit). `LICENSE-MUSIC.md` says so, and now also lets videos and streams of the game use its
  music.
- **The history:** clean. All 377 commits checked: no keys, tokens, passwords, saves or private files. One thing:
  every commit carries your email as its author, which GitHub shows on a public repo (normal; if you'd rather
  not, new commits can use GitHub's no-reply address, and old ones would need their history rewritten).
- **The title:** the third, noted. **The voices:** the video pass will stop at the samples for your pick.
- **Still yours when the repo goes public:** turn on private vulnerability reporting in its settings."""


def fragments() -> str:
    d = ROOT / "docs" / "review"
    return "\n".join(p.read_text(encoding="utf-8") for p in sorted(d.glob("*.html"))) if d.exists() else ""


def main() -> None:
    shutil.rmtree(OUT, ignore_errors=True)
    OUT.mkdir(parents=True, exist_ok=True)  # (a shell may be sitting in it)
    data = {"sounds": sounds() + made_sounds() if SHOW_SOUNDS else [], "music": music() if SHOW_SOUNDS else [],
            "run": run_list() if RUN_READY else {}, "dragons": dragons() if DRAGONS else [],
            "people": {}, "looks": looks() if LOOKS else {}, "plans": banners(), "plansHead": PLANS_HEAD}
    page = (Path(__file__).with_name("review_template.html").read_text(encoding="utf-8")
            .replace("/*DATA*/null", json.dumps(data, ensure_ascii=False))
            .replace("/*TITLE*/", PAGE_TITLE)
            .replace("<!--SECTIONS-->", fragments()))
    (OUT / "index.html").write_text(page, encoding="utf-8")
    n = sum(len(s["files"]) for s in data["sounds"])
    print(f"[review] {len(data['sounds'])} sounds ({n} takes), {len(data['music'])} music prompts, "
          f"{len(data['dragons'])} dragons -> {OUT / 'index.html'}")


if __name__ == "__main__":
    main()
