// Generated by tools/story/build_story.py from story/*.story: do not edit by hand.
// The story's names for the game's code (D137).
#pragma once

#include "core/types.hpp"

namespace ec::story {

enum Quest : u8 {
    kQKeepersApprentice = 0,
    kQMarketDay = 1,
    kQHilltop = 2,
    kQMeadow = 3,
    kQColdHeights = 4,
    kQWings = 5,
    kQTrailhead = 6,
    kQLanternFestival = 7,
    kQTwoByTwo = 8,
    kQFigMap = 9,
    kQSirFlaps = 10,
    kQTea = 11,
    kQCoveMeet = 12,
    kQCoveWhiskers = 13,
    kQHollowCount = 14,
    kQHollowDeeper = 15,
    kQHollowWarden = 16,
    kQLeagueSignup = 17,
    kQLeagueEmber = 18,
    kQLeagueFlame = 19,
    kQLeagueBlaze = 20,
    kQLeagueStarfire = 21,
    kQPageantInvite = 22,
    kQPageantDazzle = 23,
    kQPageantEmber = 24,
    kQPageantFlame = 25,
    kQPageantBlaze = 26,
    kQPageantStar = 27,
};
constexpr int kQuestCount = 28;

enum PersonId : u8 {
    kPNarrator = 0,
    kPRowan = 1,
    kPMaple = 2,
    kPBram = 3,
    kPWren = 4,
    kPPip = 5,
    kPSable = 6,
    kPFig = 7,
    kPTam = 8,
    kPTove = 9,
    kPLinnet = 10,
    kPMadder = 11,
    kPCelestine = 12,
    kPPrimrose = 13,
    kPMarigold = 14,
    kPRook = 15,
    kPSeraphine = 16,
    kPSolenne = 17,
    kPCustard = 18,
    kPCinder = 19,
};
constexpr int kPersonIdCount = 20;

enum FlagId : u16 {
    kFMetNarrator = 0,
    kFMetRowan = 1,
    kFMetMaple = 2,
    kFMetBram = 3,
    kFMetWren = 4,
    kFMetPip = 5,
    kFMetSable = 6,
    kFMetFig = 7,
    kFMetTam = 8,
    kFMetTove = 9,
    kFMetLinnet = 10,
    kFMetMadder = 11,
    kFMetCelestine = 12,
    kFMetPrimrose = 13,
    kFMetMarigold = 14,
    kFMetRook = 15,
    kFMetSeraphine = 16,
    kFMetSolenne = 17,
    kFMetCustard = 18,
    kFMetCinder = 19,
    kFNestSettled = 20,
    kFNestHatched = 21,
    kFFlapsFound = 22,
    kFHoneyTaken = 23,
    kFAct1Done = 24,
    kFOnceRowan7bfa2a4a = 25,
    kFOnceRowanF63af0a2 = 26,
    kFOnceRowan863a6dac = 27,
    kFOnceRowanFb4832ad = 28,
    kFOnceRowan7f261466 = 29,
    kFCinderWoke = 30,
    kFOnceRowan79156406 = 31,
    kFOnceRowanE1e462b0 = 32,
    kFOnceRowan0a2e152f = 33,
    kFFigFriend = 34,
    kFOnceMapleFf0ef3fd = 35,
    kFOnceMaple1c9aab8b = 36,
    kFOnceFig9d91294f = 37,
    kFFigToldTam = 38,
    kFOnceFig11c9989c = 39,
    kFOnceBramDb33da1c = 40,
    kFOnceBram5bfe0205 = 41,
    kFOncePipE95a8b47 = 42,
    kFPipRodeTalk = 43,
    kFOncePip8cf241b5 = 44,
    kFOnceWrenB69a411c = 45,
    kFCaughtWhiskers = 46,
    kFOnceTam35d991de = 47,
    kFOnceTove94906144 = 64,
    kFOnceToveE54eba31 = 49,
    kFOnceWren1ba6bddd = 50,
    kFOnceMarigoldB0ba5117 = 51,
    kFOnceRook959c4fb9 = 52,
    kFOnceSeraphine821d5a16 = 53,
    kFOnceSolenne0408fd81 = 54,
    kFMigrated = 55,
    kFBeatPrimrose = 62,
    kFPageantExplained = 56,
    kFDressedUp = 57,
    kFLookWon = 58,
    kFOnceCelestine55d01822 = 59,
    kFOnceLinnet9f3765cc = 60,
    kFOncePrimrose009622b5 = 61,
    kFOncePrimrose6a5adfd8 = 63,
};
constexpr int kFlagIdCount = 64;

enum VarId : u8 {
    kVPagesFound = 0,
    kVPages = 1,
};
constexpr int kVarIdCount = 2;

enum EventId : u8 {
};
constexpr int kEventIdCount = 0;

enum LetterId : u8 {
    kLNewsLivingValley = 0,
    kLRowanHello = 1,
    kLRowanHilltop = 2,
    kLCelestineInvite = 3,
    kLFigTam = 4,
    kLMapleFlyer = 5,
    kLPipDrawing = 6,
    kLBramPresent = 7,
    kLSableMoonpetal = 8,
    kLRowanFestival = 9,
    kLCinderNote = 10,
    kLFigSketch = 11,
    kLWrenFlame = 12,
    kLMarigoldSeeds = 13,
    kLRookLetter = 14,
    kLWrenBlaze = 15,
    kLSeraphineNote = 16,
    kLWrenStarfire = 17,
    kLSolenneBeyond = 18,
    kLToveNumbers = 19,
    kLCelestineEmber = 20,
    kLCelestineFlame = 21,
    kLCelestineBlaze = 22,
    kLPrimroseChallenge = 23,
    kLPrimroseTruce = 24,
    kLLinnetStock = 25,
    kLTamWhiskers = 26,
    kLRowanAfter = 27,
};
constexpr int kLetterIdCount = 28;

constexpr int kPickupCount = 10;
constexpr int kGroupCount = 1;

constexpr u8 kGPage = 0;

}  // namespace ec::story
