"""Generate the game's table of kinds, plans, elements, manners and traits from tools/dragons
(pure Python): src/core/kinds_data.inc, included by src/core/kinds.cpp.

  python tools/dragons/gen_tables.py [--check]      (--check: fail if the file is out of date)

Colours: the kinds' linear 0..1 RGB (what the review renders show through Blender's sRGB view)
become sRGB bytes, which the 3DS shows as they are. The eggs' colours (EGG["colors"]) are
display values already (egg_model.py previews them so) and go in as they are.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import dragons  # noqa: E402
from dragons import lore  # noqa: E402

OUT = os.path.join(ROOT, "src", "core", "kinds_data.inc")
SLOTS = ("base", "accent", "pattern", "horn", "membrane", "iris", "pupil", "glint", "glow", "tongue")
CHANNEL = {None: -1, "r": 0, "g": 1, "b": 2}
RARITY = {"common": "Rarity::Common", "uncommon": "Rarity::Uncommon", "rare": "Rarity::Rare"}


def srgb(c):
    c = max(0.0, min(1.0, c))
    v = c * 12.92 if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055
    return int(round(v * 255))


def rgb(c):
    return "{%d, %d, %d}" % tuple(srgb(x) for x in c)


def display_rgb(c):
    """Colours already given as shown (the eggs' EGG["colors"], as egg_model.py previews them)."""
    return "{%d, %d, %d}" % tuple(int(round(max(0.0, min(1.0, x)) * 255)) for x in c)


def cf(x):
    """A C++ float literal."""
    t = repr(float(x))
    return (t if ("." in t or "e" in t) else t + ".0") + "f"


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def variant_colors(v):
    out = dict(v)
    out.setdefault("pupil", (0.06, 0.03, 0.05))
    out.setdefault("glint", (1.0, 1.0, 1.0))
    out.setdefault("tongue", (0.93, 0.45, 0.55))
    out.setdefault("horn", out["accent"])
    out.setdefault("membrane", tuple(0.55 * c + 0.45 * a for c, a in zip(out["base"], out["accent"])))
    out.setdefault("pattern", out["base"])
    return out


def main():
    kinds = dragons.all_kinds()
    plan_names = sorted({k.META["plan"] for k in kinds})
    plans = [dragons.plan(p) for p in plan_names]
    names = [k.META["name"] for k in kinds]
    manners = list(lore.MANNERS)
    traits = list(lore.TRAITS)
    lines = ["// Generated by tools/dragons/gen_tables.py from tools/dragons: do not edit by hand.", ""]
    lines.append("const char* const kElementNames[] = {%s};" % ", ".join(cstr(e[0]) for e in lore.ELEMENTS))
    lines.append("const Rgb kElementGlow[] = {%s};" % ", ".join(rgb(e[1]) for e in lore.ELEMENTS))
    lines.append("const char* const kMannerNames[] = {%s};" % ", ".join(cstr(m) for m in manners))
    lines.append("const u8 kMannerNudge[][2] = {%s};" % ", ".join(
        "{%d, %d}" % (lore.STATS.index(up), lore.STATS.index(down)) for up, down in lore.MANNERS.values()))
    lines.append("const char* const kTraitNames[] = {%s};" % ", ".join(cstr(t) for t in traits))
    lines.append("const u8 kTraitTier[] = {%s};" % ", ".join(str(lore.TIERS.index(v[0])) for v in lore.TRAITS.values()))
    lines.append("")
    lines.append("const PlanInfo kPlans[] = {")
    for p in plans:
        seat_bone, seat = p.SEAT
        lines.append("    {%s, {%s}, %s, {%s, %s, %s}}," % (cstr(p.NAME), ", ".join(cstr(c) for c in p.CONTACTS),
                                                         cstr(seat_bone), *(cf(v) for v in seat)))
    lines.append("};")
    lines.append("")
    lines.append("const KindInfo kKinds[] = {")
    for k in kinds:
        m = k.META
        lore.check_meta(m)
        els = m["element"] if isinstance(m["element"], (tuple, list)) else (m["element"],)
        el = [lore.ELEMENT_NAMES.index(e) for e in els] + [0]
        parents = [names.index(p) if p in names else -1 for p in m.get("parents", ())] + [-1, -1]
        stats = ", ".join(str(m["stats"][s]) for s in lore.STATS)
        mann = [manners.index(x) for x in m["manners"]][:4]
        trt = [traits.index(x) for x in m["traits"]][:6]
        lines.append("    {%s, %s, %d, {%d, %d}, %d, {%d, %d}, %s, %d, %s, {%s}," % (
            cstr(m["name"]), cstr(m["title"]), m["dex"], el[0], el[1], len(els), parents[0], parents[1],
            RARITY[m["rarity"]], plan_names.index(m["plan"]), cf(m.get("size", 1.0)), stats))
        lines.append("     {%s}, %d, {%s}, %d, %s," % (", ".join(map(str, mann + [0] * (4 - len(mann)))), len(mann),
                                                     ", ".join(map(str, trt + [0] * (6 - len(trt)))), len(trt),
                                                     cstr(m["blurb"])))
        lines.append("     {")
        egg = k.EGG.get("colors", [])
        for vi, v in enumerate(k.VARIANTS):
            c = variant_colors(v)
            e = egg[vi] if vi < len(egg) else (c["accent"], c["base"])
            lines.append("         {%s, {%s}, %d, %d, {%s, %s}}," % (
                cstr(v["name"]), ", ".join(rgb(c[s]) for s in SLOTS), CHANNEL[v.get("pattern_channel")],
                CHANNEL[v.get("glow_channel")], display_rgb(e[0]), display_rgb(e[1])))
        lines.append("     },")
        scales = [cf(k.FORMS[f].get("export_scale", 1.0)) for f in ("hatchling", "grown")]
        lines.append("     %d, %s, {%s, %s}}," % (m.get("rare_variant", 3), "true" if m.get("rare_replaces", True) else "false",
                                               *scales))
    lines.append("};")
    text = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if old != text:
            print(f"[gen] {OUT} is out of date: run python tools/dragons/gen_tables.py")
            sys.exit(1)
        print(f"[gen] {OUT} up to date")
        return
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print(f"[gen] {OUT}: {len(kinds)} kinds, {len(plans)} plans, {len(traits)} traits")


if __name__ == "__main__":
    main()
