"""Writes tests/autotest/kinds_all.txt: every kind in the den as a hatchling, then grown in its
first and its rare colouring (dev menu page 1: Next kind at 82,231, Kind colouring at 238,231;
Next stage at 82,106). Plain Python; run after tools/dragons/gen_tables.py.

  python tools/dragons/make_autotest.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import dragons  # noqa: E402

NEXT_KIND, COLOURING, NEXT_STAGE = "tap 82 231", "tap 238 231", "tap 82 106"


def dev(*taps):
    out = ["key SELECT", "wait 0.3"]
    for t in taps:
        out += [t, "wait 0.3"]
    return out + ["key SELECT"]


def main():
    kinds = [k.META["name"] for k in dragons.all_kinds()]
    n = len(kinds)
    lines = ["# Every new kind in the den (the dragon revamp, D77-D79): generated by",
             "# tools/dragons/make_autotest.py. As a hatchling, then grown in its first and rare colourings.",
             "overlay on", "wait 2.5", "name Noah", "tap 160 107", "wait 1.5", "tap 160 120", "tap 160 120", "wait 2",
             "key SELECT", "wait 0.3", "tap 238 81", "key SELECT", "name Rill", "wait 12"]
    for i, k in enumerate(kinds):
        lines += dev(NEXT_KIND) + ["wait 3", f"shot h{i + 1:02d}-{k}"]
    lines += dev(NEXT_KIND)  # back to its own look
    lines += dev(NEXT_STAGE, NEXT_STAGE, NEXT_STAGE) + ["wait 3"]
    for i, k in enumerate(kinds):
        lines += dev(NEXT_KIND) + ["wait 3", f"shot g{i + 1:02d}-{k}"]
        lines += dev(COLOURING, COLOURING, COLOURING) + ["wait 3", f"shot r{i + 1:02d}-{k}-rare"]
        lines += dev(COLOURING)  # back to the first colouring
    lines.append("quit")
    path = os.path.join(ROOT, "tests", "autotest", "kinds_all.txt")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"[autotest] {path}: {n} kinds, {3 * n} shots")


if __name__ == "__main__":
    main()
